name: Publish pdf CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
 
    - name: Compile main
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex

    - name : publish pdf
      uses: actions/upload-artifact@v2
      with:
        name: main file
        path: main.pdf
